#
# Makefile
#
# There is only 1 command, which deletes all
# files that are not to be submitted, except
# for the virtual environment (venv).
#
# Run 'make clean' before submitting the project.

.PHONY: clean
clean:
	rm -rf db.sqlite3 */*/__pycache__ */__pycache__ \
	   */*/*/__pycache__ */migrations/0*.py *.pyc
