databases:
  - name: OneOnOnedb
    plan: free
    databaseName: OneOnOne
    user: OneOnOne

services:
  - type: web
    plan: free
    name: meetq
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn OneOnOne.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: OneOnOnedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4