databases:
  - name: meetqdb
    plan: free
    databaseName: meetq
    user: meetq

services:
  - type: web
    plan: free
    name: meetq
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn meetq.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meetqdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4