export const REGISTER_URL = "meetq.onrender.com/accounts/register/";
export const LOGIN_URL = "meetq.onrender.com/accounts/login/";
export const LOGOUT_URL = "meetq.onrender.com/accounts/logout/";
export const REFRESH_URL = "meetq.onrender.com/accounts/api/token/refresh/";
export const OBTAIN_TOKEN_URL = "meetq.onrender.com/accounts/api/token/";
export const PROFILE_URL = "meetq.onrender.com/accounts/profile/view/";
export const PROFILE_EDIT_URL = "meetq.onrender.com/accounts/profile/edit/";
export const CONTACTS_VIEW_URL = "meetq.onrender.com/accounts/api/contacts/";
export const ALL_CALENDARS_URL = "meetq.onrender.com/calendars/";
export const CALENDAR_DETAILS_URL = "meetq.onrender.com/calendar/<calendar_id>/";  // Replace <calendar_id> with actual ID when used
export const CREATE_CALENDAR_URL = "meetq.onrender.com/calendar/create/";
export const EDIT_CALENDAR_URL = "meetq.onrender.com/calendar/edit/<calendar_id>/";  // Replace <calendar_id> with actual ID when used
export const INVITE_URL = "meetq.onrender.com/invite/";
export const INVITE_RESPONSE_URL = "meetq.onrender.com/invite/response/<invitee_id>/";  // Replace <invitee_id> with actual ID when used
export const SEND_INVITE_URL = "meetq.onrender.com/send_invite/";
export const CREATE_TIMESLOT_URL = "meetq.onrender.com/timeslot/create/";