# Generated by Django 5.0.3 on 2024-03-29 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responded', models.BooleanField(default=False)),
                ('available', models.JSONField()),
                ('preferred', models.JSONField()),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='calendars.calendar')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='accounts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='accounts.contact')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='schedule.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option1', to='schedule.schedule')),
                ('option2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option2', to='schedule.schedule')),
                ('option3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option3', to='schedule.schedule')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleoptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleplannextweek', to='schedule.schedule')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleplan', to=settings.AUTH_USER_MODEL)),
                ('this_week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleplanthisweek', to='schedule.schedule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('calendar', 'contact'), name='unique_migration_host_combination'),
        ),
    ]
