# Generated by Django 5.0.3 on 2024-04-02 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendar_invited'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date', 'time_slot']},
        ),
        migrations.AddField(
            model_name='meeting',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='calendars.calendar'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.DateField(help_text='The week for this schedule'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
