# Generated by Django 5.0.4 on 2024-04-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendar_invited'),
        ('schedule', '0002_alter_meeting_options_meeting_calendar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='week',
        ),
        migrations.RemoveField(
            model_name='scheduleplan',
            name='next_week',
        ),
        migrations.RemoveField(
            model_name='scheduleplan',
            name='this_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='calendars',
            field=models.ManyToManyField(related_name='schedules', to='calendars.calendar'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='isFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='matches',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='meetings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleplan', to='schedule.schedule'),
        ),
    ]
