# Generated by Django 5.0.3 on 2024-03-29 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('color', models.CharField(max_length=7)),
                ('duration', models.IntegerField()),
                ('owners_available', models.JSONField(default=list)),
                ('owners_preferred', models.JSONField(default=list)),
                ('deadline', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_responded', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='calendars.calendar')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='accounts.contact')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='invited',
            field=models.ManyToManyField(related_name='calendars', to='calendars.invitee'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_preferred', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='calendars.calendar')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='calendars.invitee')),
            ],
        ),
    ]
