# Generated by Django 5.0.3 on 2024-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='invited',
            field=models.ManyToManyField(related_name='calendars', to='accounts.contact'),
        ),
    ]
