# Generated by Django 5.0.4 on 2024-04-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendar_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='calendars.invitee'),
        ),
    ]
