# Generated by Django 5.0.4 on 2024-04-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_alter_timeslot_invitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='number_invitees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='number_responded',
            field=models.IntegerField(default=0),
        ),
    ]
