# Generated by Django 5.0.4 on 2024-04-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_calendar_number_invitees_calendar_number_responded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='number_invitees',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='number_responded',
        ),
    ]
